site_name: Brady Smith
site_url: https://bradyasmith.com
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: assets/avatar.jpg
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: blue

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: indigo
      accent: blue

markdown_extensions:
  - admonition
  - md_in_html
  - toc:
      permalink: true

copyright: Copyright &copy; 2025 Brady Smith