site_name: Brady Smith
site_url: https://bradyasmith.com
theme:
  name: material
  logo: assets/images/avatar.png
  favicon: assets/images/book-outline.svg
  features:
      - navigation.instant
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections

  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: indigo

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: indigo
      accent: blue

nav:
  - About: index.md
  - Portfolio: 
    - Overview: portfolio/index.md
    - Writing samples:
      - portfolio/writing-samples/sharp.md
      - Diataxis templates: 
        - Overview: portfolio/writing-samples/diataxis-templates/index.md
        - How-to template: portfolio/writing-samples/diataxis-templates/how-to.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - tags


copyright: Copyright &copy; 2025 Brady Smith